### ISSUE TITLE
Bug in integrated model

### ISSUE THREAD

**Issue by dslramsey** [mfidino/integrated-occupancy-model#1]
Hi @mfidino,  I recently came across your blog post about fitting integrated SDMS with presence only + presence absence data.  It was an enjoyable read so I tried fitting the model myself in JAGS.  However, when I fit a modified version of the model to just the presence only data (so excluding the presence/absence data & model), I was getting results that didn't make sense.  Specifically  estimates of the intercept for the latent process of zero with wide credible intervals.   Upon looking further I believe there is a bug in the presence-only log-likelihood.

The original code had this for the log-likelihood
```
log(lambda[po_pixel[po]]*b[po_pixel[po]]) - log(po_denominator)
 
```
However, I think the log-likelihood should be this

```
log(lambda[po_pixel[po]]*b[po_pixel[po]]) - po_denominator
```
Which is what you get when you take the log of equation 3 in Koshkina et al.  This also matches the log-likelihood given in Dorazio et al 2014.   I think this wasn't getting picked up because the parameter estimates were being dominated by the presence/absence data.

Cheers
Dave Ramsey

**Comment by oliviergimenez** [comment]
Hi @mfidino,
Nice post ! I'm using your code to fit a IPPP model to presence-only data only, and I couldn't recover the parameters I used to simulate data. However, when I accounted for @dslramsey's remark, everything worked like a charm. 
Cheers,
Olivier

**Comment by mfidino** [comment]
Wow, my work's email must have sent @dslramsey's comment to my junk box as I had never seen this issue until now! I will confirm the error when I get a chance and then modify the code / blog to reflect those changes. Thanks for catching this!

**Comment by mfidino** [comment]
I have gone ahead and updated the code here as well as the blog post. Sorry for taking LITERAL years to actually address this. I had not seen the issue that Dave brought up, and thanks Olivier for boosting the signal on this one!

Mason
